#pragma once

// Конфігурація таблиці
#define ROWS		 3
#define COLS		 3
#define FIELD_WIDTH  1
#define FIELD_HEIGHT 1

// Кольори консолі
#define TEXT_ATTR				0 | FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_GREEN
#define HELP_BAR			    0 | BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_RED
#define SELECTED_BUTTON_ATTR	0 | BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN
#define BUTTON_ATTR			    0 | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_GREEN
